"""
ChromaVectorStore class for interacting with ChromaDB.
"""

import logging
import uuid
from typing import Any, Dict, List

import config as config
from embedding_service import SentenceTransformerEmbeddings
from langchain_core.callbacks import CallbackManagerForRetrieverRun
from langchain_core.documents import Document
from langchain_core.retrievers import BaseRetriever

import chromadb
from chromadb import EmbeddingFunction

logger = logging.getLogger(__name__)


class CustomChromaEmbedder(EmbeddingFunction):
    def __init__(self, provider: SentenceTransformerEmbeddings):
        self.provider = provider

    def __call__(self, input: List[str]) -> List[List[float]]:
        return self.provider.embed_documents(input)


class ChromaVectorStore:
    def __init__(
        self,
        hostname: str = config.CHROMA_DB_HOST,
        port: int = config.CHROMA_DB_PORT,
        collection_name: str = config.CHROMA_COLLECTION_NAME,
        embedding_provider: SentenceTransformerEmbeddings = None,  # Pass instance
    ):
        """
        Initializes the ChromaDB client and collection.

        Args:
            path: Path to the directory where ChromaDB data will be persisted.
            collection_name: Name of the collection within ChromaDB.
            embedding_provider: An instance of SentenceTransformerEmbeddings.
        """
        logger.info("Connecting to ChromaDB at %s:%d", hostname, port)
        self.client = chromadb.HttpClient(host=hostname, port=port)

        self.embedding_provider = (
            embedding_provider or SentenceTransformerEmbeddings()
        )  # Use passed or create new

        # Wrap the custom embedding function for ChromaDB
        # self.chroma_embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
        #      model_name=self.embedding_provider.model.config.name_or_path # Get name from loaded model
        # )
        self.chroma_embedding_function = CustomChromaEmbedder(self.embedding_provider)

        logger.info("Getting or creating ChromaDB collection: %s", collection_name)
        try:
            self.collection = self.client.get_or_create_collection(
                name=collection_name,
                embedding_function=self.chroma_embedding_function,
                # metadata={"hnsw:space": "cosine"}
            )
            logger.info("Collection '%s' ready.", collection_name)
        except Exception as e:
            logger.error(
                "Failed to get or create Chroma collection '%s': %s", collection_name, e
            )
            raise

    def add_documents(self, documents: List[Document]):
        """
        Adds documents (chunks) to the ChromaDB collection.
        Embeddings are generated by the function provided during collection creation.

        Args:
            documents: A list of LangChain Document objects (chunks).
                       Assumes page_content contains the text to be embedded.
        """
        if not documents:
            logger.warning("No documents provided to add.")
            return

        logger.info(
            "Adding %d documents to collection '%s'...",
            len(documents),
            self.collection.name,
        )

        ids = [str(uuid.uuid4()) for _ in documents]
        texts = [doc.page_content for doc in documents]
        # Ensure metadata values are Chroma-compatible types (str, int, float, bool)
        metadatas = [
            {
                k: str(v) if not isinstance(v, (str, int, float, bool)) else v
                for k, v in doc.metadata.items()
            }
            for doc in documents
        ]

        try:
            # ChromaDB's add method will use the collection's embedding function
            self.collection.add(ids=ids, documents=texts, metadatas=metadatas)
            logger.info("Successfully added %d documents.", len(documents))
        except Exception as e:
            logger.error("Failed to add documents to Chroma collection: %s", e)

    def search(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
        """
        Performs a similarity search in the ChromaDB collection.

        Args:
            query: The search query string.
            k: The number of top results to retrieve.

        Returns:
            A list of dictionaries, each containing 'document', 'metadata', and 'distance'.
            Returns empty list on error or no results.
        """
        logger.info(
            "Performing search in collection '%s' for query: '%s...' (k=%d)",
            self.collection.name,
            query[:50],
            k,
        )
        try:
            # The query text is automatically embedded by the collection's embedding function
            results = self.collection.query(
                query_texts=[query],
                n_results=k,
                include=[
                    "documents",
                    "metadatas",
                    "distances",
                ],  # Request desired fields
            )

            # Structure the results
            search_results = []
            if results and results.get("ids") and results["ids"][0]:
                for i in range(len(results["ids"][0])):
                    search_results.append(
                        {
                            "id": results["ids"][0][i],
                            "document": (
                                results["documents"][0][i]
                                if results.get("documents")
                                else None
                            ),
                            "metadata": (
                                results["metadatas"][0][i]
                                if results.get("metadatas")
                                else None
                            ),
                            "distance": (
                                results["distances"][0][i]
                                if results.get("distances")
                                else None
                            ),
                            "similarity": (
                                1.0 - results["distances"][0][i]
                                if results.get("distances")
                                else None
                            ),
                        }
                    )
                logger.info("Found %d results.", len(search_results))
            else:
                logger.info("No results found.")

            return search_results

        except Exception as e:
            logger.error("Error during search in Chroma collection: %s", e)
            return []

    def get_collection_count(self) -> int:
        """Returns the number of items in the collection."""
        try:
            return self.collection.count()
        except Exception as e:
            logger.error("Error getting collection count: %s", e)
            return 0

    def clear_collection(self):
        """Deletes all items from the collection."""
        logger.warning(
            "Attempting to clear all items from collection: %s", self.collection.name
        )
        try:
            # This is inefficient for large collections. A better way is delete/recreate.
            count = self.collection.count()
            if count > 0:
                ids_to_delete = self.collection.get(limit=count)[
                    "ids"
                ]  # Get all IDs (might be slow)
                if ids_to_delete:
                    self.collection.delete(ids=ids_to_delete)
                    logger.info(
                        "Cleared %d items from collection '%s'.",
                        len(ids_to_delete),
                        self.collection.name,
                    )
                else:
                    logger.info(
                        "Collection '%s' was already empty or failed to retrieve IDs.",
                        self.collection.name,
                    )
            else:
                logger.info("Collection '%s' is already empty.", self.collection.name)
        except Exception as e:
            logger.error("Error clearing collection '%s': %s", self.collection.name, e)

    def get_relevant_documents(
        self,
        query,
        score_threshold: float = None,
        k: int = 5,
        **kwargs,
    ) -> List[Document]:
        """
        Retrieves relevant documents from the collection based on the query.
        Filters results based on the score_threshold if provided.

        Args:
            query: The search query string.
            run_manager: CallbackManagerForRetrieverRun instance.
            score_threshold: The minimum similarity score to consider.
            k: The number of top results to retrieve.

        Returns:
            A list of LangChain Document objects.
        """
        search_results = self.search(query, k=k)
        if not search_results:
            return []

        relevant_documents = []
        for result in search_results:
            if score_threshold and result["similarity"] < score_threshold:
                continue

            # Create a Document object with the retrieved data
            doc = Document(
                page_content=result["document"],
                metadata=result["metadata"],
                score=result["similarity"],
            )
            relevant_documents.append(doc)

        return relevant_documents


class CustomChromaRetriever(BaseRetriever):
    def __init__(self, chroma_store: ChromaVectorStore):
        self.chroma_store = chroma_store

    def _get_relevant_documents(
        self,
        query: str,
        *args,
        run_manager: CallbackManagerForRetrieverRun,
        score_threshold: float = None,
        k: int = 5,
        **kwargs,
    ) -> List[Document]:
        """
        Retrieves relevant documents from the collection based on the query.
        Filters results based on the score_threshold if provided.
        Refer - https://python.langchain.com/docs/how_to/custom_retriever/

        Args:
            query: The search query string.
            run_manager: CallbackManagerForRetrieverRun instance.
            score_threshold: The minimum similarity score to consider.
            k: The number of top results to retrieve.

        Returns:
            A list of LangChain Document objects.
        """
        return self.chroma_store.get_relevant_documents(
            query,
            run_manager=run_manager,
            score_threshold=score_threshold,
            k=k,
        )
